spring:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        temp.use_jdbc_metadata_defaults: false
        dialect: org.hibernate.dialect.MySQL8Dialect
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      idle-timeout: 300000
      maximum-pool-size: 10
      connection-timeout: 60000
      initialization-fail-timeout: 30000
      max-lifetime: 1800000
      minimum-idle: 5
  security:
    oauth2:
      client:
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: profile,email
  application:
    name: generation_ai_java
  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 100MB

logging:
  level:
    root: INFO

jwt:
  expiration-time: '3600000'
  refresh-expiration-time: '86400000'
  secret: ${JWT_SECRET}

redirect:
  url: ${REDIRECT_URL}
