spring:
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
  security:
    oauth2:
      client:
        registration:
          google:
            redirect-uri: http://localhost:8080/login/oauth2/code/google
